module.exports = {
  'Argentina': ':flag-ar:',
  'Australia': ':flag-au:',
  'Belgium': ':flag-be:',
  'Brazil': ':flag-br:',
  'Colombia': ':flag-co:',
  'Costa Rica': ':flag-cr:',
  'Croatia': ':flag-hr:',
  'Denmark': ':flag-dk:',
  'Egypt': ':flag-eg:',
  'England': ':flag-england:',
  'France': ':flag-fr:',
  'Germany': ':flag-de:',
  'Iceland': ':flag-is:',
  'Iran': ':flag-ir:',
  'Japan': ':flag-jp:',
  'Korea Republic': ':flag-kr:',
  'Mexico': ':flag-mx:',
  'Morocco': ':flag-ma:',
  'Nigeria': ':flag-ng:',
  'Panama': ':flag-pa:',
  'Peru': ':flag-pe:',
  'Poland': ':flag-pl:',
  'Portugal': ':flag-pt:',
  'Russia': ':flag-ru:',
  'Saudi Arabia': ':flag-sa:',
  'Senegal': ':flag-sn:',
  'Serbia': ':flag-rs:',
  'Spain': ':flag-es:',
  'Sweden': ':flag-se:',
  'Switzerland': ':flag-ch:',
  'Tunisia': ':flag-tn:',
  'Uruguay': ':flag-uy:',
};
